{
  "_": {
    "CDF.FailedCDFRead": "cdawmeta.io.read_cdf_depend_0s('https://cdaweb.gsfc.nasa.gov/sp_phys/data/wind/orbit/pre_or/1994/wi_or_pre_19940807_v02.cdf') failed with error: [Errno 22] Invalid argument\n\nTraceback (most recent call last):\n  File \"~/git/hapi/cdawmeta/cdawmeta/generators/cadence.py\", line 116, in _depend_0s_counts\n    depend_0_names = cdawmeta.io.read_cdf_depend_0s(url, logger=logger, use_cache=use_cache)\n  File \"~/git/hapi/cdawmeta/cdawmeta/io/read_cdf.py\", line 44, in read_cdf_depend_0s\n    info = cdffile.cdf_info()\n  File \"~/miniconda3/lib/python3.9/site-packages/cdflib/cdfread.py\", line 201, in cdf_info\n    self._get_attnames(),\n  File \"~/miniconda3/lib/python3.9/site-packages/cdflib/cdfread.py\", line 766, in _get_attnames\n    adr_info = self._read_adr(position)\n  File \"~/miniconda3/lib/python3.9/site-packages/cdflib/cdfread.py\", line 957, in _read_adr\n    return self._read_adr2(position)\n  File \"~/miniconda3/lib/python3.9/site-packages/cdflib/cdfread.py\", line 991, in _read_adr2\n    self._f.seek(byte_loc, 0)\nOSError: [Errno 22] Invalid argument\n"
  }
}